services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'vedcommerce'
      MYSQL_USER: 'Eizrah'
      MYSQL_PASSWORD: 'Eizrah17mars2003!'
      MYSQL_ROOT_PASSWORD: 'rootpassword' # Mettez un mot de passe fort si exposé
    ports:
      - "3307:3306" # Mappé sur 3307 pour ne pas interférer avec le port 3306 de l'hôte (ou de wusu)
    volumes:
      - db_data:/var/lib/mysql
      # Ce volume charge le fichier SQL pour l'initialisation de la base
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "Eizrah", "-pEizrah17mars2003!"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s

  web:
    build: ./Backend/VEDCommerce
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./Backend/VEDCommerce:/app
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=vedcommerce
      - DB_USER=Eizrah
      - DB_PASSWORD=Eizrah17mars2003!
      - DB_PORT=3306
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
