# Generated by Django 6.0.4 on 2026-04-16 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id_article', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('note', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id_facture', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nom_prenom', models.CharField(max_length=100)),
                ('numero_telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos_personnes/')),
                ('num_cin', models.CharField(blank=True, max_length=20, null=True)),
                ('date_naissance', models.DateField()),
                ('genre', models.CharField(choices=[('homme', 'Homme'), ('femme', 'Femme')], max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id_commande', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('prix_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='VedBackend.article')),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='VedBackend.client')),
            ],
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id_commentaire', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('id_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='VedBackend.article')),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='VedBackend.client')),
            ],
        ),
        migrations.CreateModel(
            name='Fichier',
            fields=[
                ('id_fichier', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=50)),
                ('taille', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichiers', to='VedBackend.article')),
            ],
        ),
        migrations.CreateModel(
            name='Vendeur',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nom_prenom', models.CharField(max_length=100)),
                ('numero_telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos_personnes/')),
                ('num_cin', models.CharField(blank=True, max_length=20, null=True)),
                ('date_naissance', models.DateField()),
                ('genre', models.CharField(choices=[('homme', 'Homme'), ('femme', 'Femme')], max_length=10)),
                ('etat', models.CharField(choices=[('En attente', 'En attente'), ('Actif', 'Actif'), ('Bloqué', 'Bloqué')], max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Vendeurs',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='id_vendeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='VedBackend.vendeur'),
        ),
    ]
