# Generated by Django 6.0.4 on 2026-04-25 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id_article', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('note', models.FloatField()),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('taille', models.CharField(max_length=50)),
                ('marque', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nom_prenom', models.CharField(max_length=100)),
                ('numero_telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos_personnes/')),
                ('genre', models.CharField(choices=[('M', 'Masculin'), ('F', 'Feminin')], max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id_facture', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('date_paiement', models.DateField()),
                ('prix_total_commande', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('personne_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='VedBackend.personne')),
            ],
            bases=('VedBackend.personne',),
        ),
        migrations.CreateModel(
            name='Vendeur',
            fields=[
                ('personne_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='VedBackend.personne')),
                ('etat', models.CharField(choices=[('En attente', 'En attente'), ('Actif', 'Actif'), ('Bloqué', 'Bloqué')], default='En attente', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Vendeurs',
            },
            bases=('VedBackend.personne',),
        ),
        migrations.CreateModel(
            name='Fichier',
            fields=[
                ('id_fichier', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=50)),
                ('taille', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichiers', to='VedBackend.article')),
            ],
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id_commentaire', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('id_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='VedBackend.article')),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='VedBackend.client')),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id_commande', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('prix_total_article', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='VedBackend.article')),
                ('id_facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='VedBackend.facture')),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='VedBackend.client')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='id_vendeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='VedBackend.vendeur'),
        ),
        migrations.CreateModel(
            name='Authentification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('id_personne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VedBackend.personne')),
            ],
            options={
                'unique_together': {('id_personne', 'email')},
            },
        ),
    ]
