# Generated by Django 6.0.4 on 2026-05-01 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VedBackend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('pantalon', 'Pantalon'), ('short', 'Short'), ('tshirt', 'T-shirt'), ('debardeur', 'Débardeur'), ('chemise', 'Chemise'), ('robe', 'Robe'), ('jupe', 'Jupe'), ('sweat', 'Sweat'), ('ensemble', 'Ensemble'), ('maillot', 'Maillot de bain')], default='tshirt', max_length=50),
        ),
        migrations.AddField(
            model_name='article',
            name='condition',
            field=models.CharField(choices=[('Neuf', 'Neuf'), ('Occasion', 'Occasion')], default='Neuf', max_length=50),
        ),
        migrations.AddField(
            model_name='article',
            name='etat_article',
            field=models.CharField(choices=[('Disponnible', 'Dispo'), ('Epuisé', 'Ep')], default='Dispo', max_length=50),
        ),
        migrations.AddField(
            model_name='article',
            name='quantite',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
