# Generated by Django 6.0.4 on 2026-04-23 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VedBackend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendeur',
            name='etat',
            field=models.CharField(choices=[('En attente', 'En attente'), ('Actif', 'Actif'), ('Bloqué', 'Bloqué')], default='En attente', max_length=50),
        ),
    ]
